Add a contributing file, some TOCs and a section for the showcase
magicmonkey/go-streamdeck pull request #25
Opened 2020-06-14 20:02 UTC by lornajane

Add a CONTRIBUTING file to show how to use the project locally, encourage bugs/issues and patches, and point people to the showcase.

Fixes #14

2020-06-14 20:04 UTC, magicmonkey requested changes
Looks good, thanks!  Couple of typos to fix, otherwise is great.

2020-06-14 20:04 UTC, magicmonkey commented on CONTRIBUTING.md
> +-
Erroneous bullet point, to be removed

2020-06-14 20:04 UTC, magicmonkey commented on CONTRIBUTING.md
> +You are very welcome to use this project within the terms of the license. We would love to have you in our showcase, please open a pull request to update the `REAMDME.md` file with a link to your pro
Typo on the word "README"

2020-06-20 16:34 UTC, lornajane commented on CONTRIBUTING.md
> +You are very welcome to use this project within the terms of the license. We would love to have you in our showcase, please open a pull request to update the `REAMDME.md` file with a link to your pro
fixed!

2020-06-20 16:35 UTC, lornajane commented on CONTRIBUTING.md
> +-
removed!

2020-06-20 16:36 UTC, merged